[versions]
agp = "8.10.0"
kotlin = "2.0.21"
coreKtx = "1.13.1"
appCompat = "1.7.0"
leanbackVersion = "1.2.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appCompat" }
androidx-leanback = { group = "androidx.leanback", name = "leanback", version.ref = "leanbackVersion" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }


